### PR TITLE
Fixed Issue 6 

### PR DESCRIPTION
**Pull request by mattwhitlock**
Fixed Issue 6 by updating Send Message over UDP.vi to utilize IP address rather than computer name.

### CODE REVIEW

**Comment by smithed** [comment]
Hey Matt,

I've recently been working with NI's legal team to figure out how to handle incoming pull requests and we are committed to finding an appropriate process to protect ourselves, contributors and also any end users (since we build and publish AMC on the tools network). Because we're in the evaluation stage I'd like to get your feedback on what we have so far.

To avoid putting our emails on a public forum, would it be possible for you to PM me on the ni community (username smithd) so I can send you the proposed details and get your thoughts?

Thanks,
Daniel

**Comment by smithed** [comment]
Hi matt,

Due to the challenges associated with merging changes made under the BSD license, we've decided to make the change to the apache license. This change is now reflected in the repository. For us to be able to merge your pull request, please do the following:
-Review the apache license and notice ("LICENSE" and "NOTICE" file in the master branch)
-Rebase your changes on the master, or merge the master's changes into yours. Because there are no file conflicts, this should be essentially identical processes.
-Once you've made that update, please post back here and we'll complete the merge process and build the code.

**Comment by mattwhitlock** [comment]
Awesome, I'll take care of that shortly.
Thanks,
Matt

**Comment by mattwhitlock** [comment]
OK. I've merged your changes into my fork and think it's ready for you to handle the pull request. Please let me know if I need to do anything else. I'm pretty new with the forking/merging/pull request process. Thanks, Matt

**Comment by smithed** [comment]
Thats all we needed, thanks. Looks good.

**Comment by smithed** [comment]
FYI I'm currently installing LV2009 on our build machine and then I'll push the changes onto VIPM.

**Comment by smithed** [comment]
uploaded to tools network 3.3.1

**Pull request merged**
